export const REQ_START = 'REQ_START';
export const GET_CONTACTUS_LIST = 'GET_CONTACTUS_LIST';
export const SUBMIT_CONTACTUS = 'SUBMIT_CONTACTUS';
export const CONTACTUS_SUCCESS = 'CONTACTUS_SUCCESS';
export const CONTACTUS_FAILURE = 'CONTACTUS_FAILURE';
